<?php
/**
 * @LICENSE_TEXT
 */

namespace Che\BuildGuild\Console;

use Symfony\Component\Console\Application;

/**
 * Class GuildApp
 *
 * @author Kirill chEbba Chebunin <iam@chebba.org>
 */
class GuildApp extends Application
{
    const NAME = 'BuildGuild';

    public function __construct($version = 'UNKNOWN')
    {
        parent::__construct(self::NAME, $version); // TODO: Change the autogenerated stub
    }

    protected function getDefaultCommands()
    {
        $commands = parent::getDefaultCommands();
        $commands[] = new Command\InstallCommand();
        $commands[] = new Command\TestCommand();
        $commands[] = new Command\StatusCommand();

        return $commands;
    }
}
